import AppKit
import Foundation

/// Decides whether and how pasteboard contents become a clipboard history item.
enum ClipboardCaptureRules {
    static let maximumTextBytes = 1_024 * 1_024
    static let maximumImageBytes = 10 * 1_024 * 1_024

    /// Types that mark content as private or temporary (see nspasteboard.org), plus Typeflux's
    /// own selection probe. Typeflux's paste writes use the transient marker too.
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "ai.gulu.app.typeflux.selection-probe"
    ]

    static func shouldIgnore(types: Set<String>) -> Bool {
        !types.isDisjoint(with: ignoredTypes)
    }

    static func capture(from contents: PasteboardContents) -> ClipboardCapture? {
        guard !shouldIgnore(types: contents.types) else { return nil }

        let fileURLs = contents.fileURLs.filter(\.isFileURL)
        if !fileURLs.isEmpty {
            return .files(fileURLs)
        }

        let text = contents.string.flatMap { $0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? nil : $0 }
        // Apps such as browsers put the image's URL next to the image; the image is what was copied.
        if let imageData = contents.imageData, text.map(ClipboardContentClassifier.isLink) ?? true {
            return image(from: imageData)
        }

        guard let text, text.utf8.count <= maximumTextBytes else { return nil }
        return .text(text)
    }

    static func image(from data: Data) -> ClipboardCapture? {
        guard let rep = NSBitmapImageRep(data: data), rep.pixelsWide > 0, rep.pixelsHigh > 0 else { return nil }
        let png = isPNG(data) ? data : rep.representation(using: .png, properties: [:])
        guard let png, png.count <= maximumImageBytes else { return nil }
        return .image(png: png, pixelWidth: rep.pixelsWide, pixelHeight: rep.pixelsHigh)
    }

    private static func isPNG(_ data: Data) -> Bool {
        data.starts(with: [0x89, 0x50, 0x4E, 0x47])
    }
}
